name: "02: Release"
description: "Default Release PR"
title: "Release/"
labels: ["Release"]
projects: []
body:
  - type: textarea
    id: qa_release
    attributes:
      label: "QA時の作業"
      description: |
        <!-- QAリリースの際に必要な作業を各開発者の方が記載してください -->
    validations:
      required: false
  - type: textarea
    id: prod_release
    attributes:
      label: "本番リリース時の作業"
      description: |
        <!-- 本番リリースの際に必要な作業を各開発者の方が記載してください -->